mysql:
  dataBase: autosign
  userName: root
  passWord: 123456
  port: 8086
  driverName: mysql
  host: url
  log-level: debug
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-life-time: 5
#  ğŸ› ï¸ğŸ”§â›ï¸ğŸ—ï¸âš™ï¸ğŸ§¬ğŸ’¡
logger:
  level: info
  prefix: '[ğŸ› ï¸]'
  director: log
  showLine: true
  logInConsole: true
mail:
  host: you-host
  port: you-port
  user: you-user
  password: you-password
  ssl: true
  local-home:         #å¯é€‰
ai:
  token: #ä½¿ç”¨è®¯é£æ˜Ÿç«å¤§æ¨¡å‹ç”ŸæˆæŠ¥å‘Š
account:
  gongxueyun: #å¯¹å·¥å­¦äº‘å•ç”¨æˆ·æ— æ•°æ®åº“æœåŠ¡æ–°å¼€è´¦å·å¯†ç ç™»å½•
    off: true                                     #off: true or false æ˜¯å¦å¼€å¯å•ç”¨æˆ·åŠ è½½ï¼Œå•ç”¨æˆ·åŠ è½½å¼€å¯æ—¶æ— æ³•ä½¿ç”¨mysqlæ•°æ®
    phone: "18862530683"                          #phone: æ‰‹æœºå·ç 
    password: "853660538hC"                     #password: å¯†ç 
    country: "ä¸­å›½"                              #country: å›½å®¶
    province: "æ±Ÿè‹çœ"                           #province: çœä»½
    city: "è‹å·å¸‚"                               #city: åŸå¸‚
    area: "å´æ±ŸåŒº"                              #area: åœ°åŒº
    latitude: "120.644724"                         #latitude: çº¬åº¦
    longitude: "31.104014"                       #longitude: ç»åº¦
    email: "853660538@qq.com"                  #email: é‚®ç®±åœ°å€
    address: "æ±Ÿè‹çœè‹å·å¸‚å´æ±ŸåŒºæ¾é™µè¡—é“ä½³ç¦¾é£Ÿå“"  #address: è¯¦ç»†åœ°å€
    type: "work"                                  #type: ç±»å‹ï¼ˆä¾‹å¦‚ï¼šhomeã€workï¼‰
  cx:
    phone:
    password:
